defaults: &defaults
  # Outgoing email configuration
  sender: 'info@hanamech.com'
  smtp_settings:
    :domain:         'heroku.com'       # the domain your emails will come from
    :address:        'smtp.sendgrid.net'  # SMTP server used to send emails
    :port:           '587'
    :authentication: :plain
    :user_name:       <%= ENV["SENDGRID_USERNAME"] %>
    :password:        <%= ENV["SENDGRID_PASSWORD"] %>
    :enable_starttls_auto: true

    # Set to true if you have Net::SMTPSyntaxError errors when sending email.
    # Rails has sometimes a problem when sending email from "Name <address@host.com>".
    # If you are having problems sending email and your host is correctly configured,
    # try setting safe_from to true. You may need to create a user account for no-reply@yourapp.com
    :safe_from: false